// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ScreenResolution","status":true,"description":"ゲームスクリーンの解像度を好きなように変更することができます","parameters":{"Screen Width":"960","Screen Height":"720"}},
{"name":"global_script","status":true,"description":"グローバルスクリプト記述プラグイン","parameters":{}},
{"name":"global_a","status":true,"description":"グローバルスクリプト記述プラグインa","parameters":{}},
{"name":"global_b","status":true,"description":"グローバルスクリプト記述プラグインb","parameters":{}},
{"name":"global_c","status":true,"description":"グローバルスクリプト記述プラグインc","parameters":{}},
{"name":"global_d","status":true,"description":"グローバルスクリプト記述プラグインd","parameters":{}},
{"name":"DebugAuto","status":false,"description":"F8コンソールを自動で出す(PC版のみ)","parameters":{}},
{"name":"UCHU_MobileOperation","status":true,"description":"スマホ操作用プラグイン。横持ち/縦持ちに対応した仮想ボタン、\r\nタッチ操作の方法を追加拡張し、スマホプレイを快適にします。","parameters":{"---PC Option---":"","PC BtnDisplay":"false","PC TouchExtend":"true","---File Path---":"","DPad Image":"./img/system/dirpad.png","ActionBtn Image":"./img/system/actionbutton.png","CancelBtn Image":"./img/system/cancelbutton.png","Num1Btn Image":"./img/system/numbutton1.png","Num3Btn Image":"./img/system/numbutton3.png","Num5Btn Image":"./img/system/numbutton5.png","Num9Btn Image":"./img/system/numbutton9.png","---Button Customize---":"","Button Opacity":"0.7","Vertical BtnZoom":"1.7","Tablet BtnZoom":"0.8","TabVertical BtnZoom":"1.1","HideButton OnMessage":"false","DPad Visible":"true","DPad Size":"120","DPad Margin":"10; 10","DPad Orientation":"left; bottom","DPad OpelationRange":"1.3","DPad DiagonalRange":"0.3","ActionBtn Visible":"true","ActionBtn Size":"60","ActionBtn Margin":"10; 70","ActionBtn Orientation":"right; bottom","CancelBtn Visible":"true","CancelBtn Size":"60","CancelBtn Margin":"70; 10","CancelBtn Orientation":"right; bottom","NumBtn Visible":"true","NumBtn Size":"60","---TouchInput Extend---":"","Flick PageUp-PageDown":"false","HoldCanvas ActionBtn":"false","OutCanvas CancelBtn":"false","OutCanvas ActionBtn":"false","--!need AnalogMove.js!--":"","Analog Move":"false","Analog Sensitivity":"1.8"}},
{"name":"ConfigureRootElement","status":true,"description":"v1.00 任意のroot要素にゲーム本体の要素を追加できるようにするpluginです","parameters":{"---General---":"","Root Element Id":""}},
{"name":"liply_WinChrome_scroll_patch","status":true,"description":"Windows Chrome scroll patch","parameters":{}},
{"name":"liply_SceneCache","status":true,"description":"Scene Cache System","parameters":{"WebGL":"1","Report Memory":"0"}},
{"name":"liply_onBitmapLoad_patch","status":false,"description":"","parameters":{}}
];
