// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"YEP_CoreEngine","status":true,"description":"v1.17 Needed for the majority of Yanfly Engine Scripts. Also\ncontains bug fixes found inherently in RPG Maker.","parameters":{"---Screen---":"","Screen Width":"960","Screen Height":"720","Scale Battlebacks":"true","Scale Title":"true","Scale Game Over":"true","Open Console":"false","Reposition Battlers":"true","GameFont Load Timer":"0","---Gold---":"","Gold Max":"99999999","Gold Font Size":"28","Gold Icon":"0","Gold Overlap":"A lotta","---Items---":"","Default Max":"99","Quantity Text Size":"28","---Stats---":"","Max Level":"99","Actor MaxHP":"9999","Actor MaxMP":"9999","Actor Parameter":"999","Enemy MaxHP":"999999","Enemy MaxMP":"9999","Enemy Parameter":"999","---Battle---":"","Animation Rate":"4","Flash Target":"false","---Font---":"","Chinese Font":"SimHei, Heiti TC, sans-serif","Korean Font":"Dotum, AppleGothic, sans-serif","Default Font":"GameFontAooni, Verdana, Arial, Courier New","Font Size":"28","Text Align":"left","---Windows---":"","Digit Grouping":"true","Line Height":"36","Icon Width":"32","Icon Height":"32","Face Width":"144","Face Height":"144","Window Padding":"18","Text Padding":"6","Window Opacity":"255","Gauge Outline":"true","Gauge Height":"18","Menu TP Bar":"false","---Window Colors---":"","Color: Normal":"0","Color: System":"16","Color: Crisis":"17","Color: Death":"18","Color: Gauge Back":"19","Color: HP Gauge 1":"20","Color: HP Gauge 2":"21","Color: MP Gauge 1":"22","Color: MP Gauge 2":"23","Color: MP Cost":"23","Color: Power Up":"24","Color: Power Down":"25","Color: TP Gauge 1":"28","Color: TP Gauge 2":"29","Color: TP Cost Color":"29"}},
{"name":"YEP_MessageCore","status":true,"description":"v1.09 Adds more features to the Message Window to customized\nthe way your messages appear and functions.","parameters":{"---General---":"","Default Rows":"4","Default Width":"Graphics.boxWidth","Face Indent":"Window_Base._faceWidth + 24","Fast Forward Key":"pagedown","Enable Fast Forward":"true","Word Wrapping":"false","Description Wrap":"false","Word Wrap Space":"false","---Font---":"","Font Name":"GameFontAooni","Font Size":"28","Font Size Change":"12","Font Changed Max":"96","Font Changed Min":"12","---Name Box---":"","Name Box Buffer X":"-28","Name Box Buffer Y":"0","Name Box Padding":"this.standardPadding() * 4","Name Box Color":"0","Name Box Clear":"false","Name Box Added Text":"\\c[0]"}},
{"name":"KeyItemAlone","status":true,"description":"アイテム選択画面で「大事なもの」のみ表示","parameters":{}},
{"name":"AooniLib","status":true,"description":"青鬼MV用ライブラリ","parameters":{}},
{"name":"OverpassTile","status":true,"description":"キャラクターが下をくぐり抜けられる橋の設定です。","parameters":{"Overpass Region ID":"255","Gateway Region ID":"254"}},
{"name":"AooniRoute","status":true,"description":"青鬼用ライブラリ(イベントのルート決定用)","parameters":{}},
{"name":"KeyItemNumber","status":true,"description":"「大事なもの」の個数表示の設定","parameters":{"KeyItem":"2","MessageWindow":"0"}},
{"name":"LargeNameWnd","status":false,"description":"名前入力画面をフルスクリーンで表示します","parameters":{"font size":"36"}},
{"name":"AooniFile","status":true,"description":"青鬼MVセーブデータ操作ルーチン","parameters":{"Escape Succession VarID":"78","Max Escape Succession VarID":"79","Gameover Number VarID":"80"}},
{"name":"TitleCommandPosition","status":false,"description":"タイトルコマンドウィンドウの位置を変更します。","parameters":{"Offset X":"30","Offset Y":"-180","Width":"240","Background":"2"}},
{"name":"SetPictureUnderMap","status":true,"description":"指定したピクチャをマップと遠景の間のレイヤに表示します","parameters":{}},
{"name":"RotatePictureEx","status":true,"description":"ピクチャを指定した角度とフレーム数で回転させます","parameters":{}},
{"name":"SetJumpHeightAndFrame","status":true,"description":"キャラクターを指定されたフレーム数と高さでジャンプさせます。","parameters":{}},
{"name":"OuterSelfSwitch","status":true,"description":"他のイベントのセルフスイッチを操作します。","parameters":{}},
{"name":"EventEffects","status":true,"description":"イベントやプレイヤーに様々な効果をセットします","parameters":{}},
{"name":"InterlockPicture","status":true,"description":"ピクチャの位置をマップやイベントなどと連動させます","parameters":{}},
{"name":"ConfigureRootElement","status":true,"description":"v1.00 任意のroot要素にゲーム本体の要素を追加できるようにするpluginです","parameters":{"---General---":"","Root Element Id":""}},
{"name":"MadeWithMv","status":false,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"madewithmv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"PlayerOverPicture","status":true,"description":"プレイヤーをピクチャの上に表示します","parameters":{}},
{"name":"AooniAchievement","status":false,"description":"アチーブメント画面を確実に表示するのに必要なコマンド群です","parameters":{}},
{"name":"DiscardImageFromCache","status":true,"description":"プラグインコマンドで明示的に画像をキャッシュから削除出来ます。","parameters":{}},
{"name":"AooniTokaigi","status":true,"description":"闘会議用","parameters":{}},
{"name":"dwango_androidpatch","status":true,"description":"Android Chromeで音が鳴らない問題を解決するプラグイン","parameters":{}}
];
